### ISSUE TITLE
Add Lesson alert notifications

### ISSUE THREAD

**Issue by CunhaPedro25** [joaoalves03/goipvc#10]

**Comment by mattcapazz** [comment]
within the app settings, allow the user to configure whether to receive notifications
1. **a configurable number of minutes** _(also in the app Settings)_ before a class begins
2. whenever there's a class delay or straight up they're cancelled 💀
3. _or_ whenever there's an app update
4. ...?

**Comment by joaoalves03** [comment]
Splitting this issue into two since lesson alerts are already ready.
