### ISSUE TITLE
Schedule labels wrong size

### ISSUE THREAD

**Issue by Spectralpt** [joaoalves03/goipvc#17]
The schedule labels are the wrong width inside the schedule menu.

**Comment by rodrigosa7** [comment]
![Simulator Screenshot - iPhone 13 Pro Max - 2023-09-29 at 02 48 50](https://github.com/joaoalves03/goipvc/assets/22347167/04302d67-5bd4-4404-a83a-92070c0f8030)

Issue fixed by: https://github.com/joaoalves03/goipvc/commit/b12da95988b20830151e21380a7baa57257b732b
