### ISSUE TITLE
TopBar in Home keeps background color from last page

### ISSUE THREAD

**Issue by CunhaPedro25** [joaoalves03/goipvc#44]
When going back to Home from a page that has scroll, the TopBar keeps the background color, which looks weird since it isn't supposed to have a background color when its in the home page (no scroll for it to change)

**Comment by rodrigosa7** [comment]
Issue solved by: https://github.com/joaoalves03/goipvc/commit/0960da4920a734f4b3391ae4c5ea4d87a561e08b
