### ISSUE TITLE
improve authentication error msgs

### ISSUE THREAD

**Issue by mattcapazz** [joaoalves03/goipvc#70]
Currently, when the username or password are incorrect during login, a toast message displays `Utilizador/Palavra-passe incorreto`. **_However_**, if any fields are left empty the toast message appears as `(start): Invalid value: Only valid value is 0: -16` when something like: `Campo ${x} não pode ser vazio.`

**Comment by rodrigosa7** [comment]
Good call! We need to keep improving this messages for more scenarios.
This issue is fixed with the commit: https://github.com/joaoalves03/goipvc/commit/4f2d03ada096db557771f10ab9fe4086f512472f
