### ISSUE TITLE
Share the same Dio instance across all requests

### ISSUE THREAD

**Issue by sousa-andre** [joaoalves03/goipvc#97]
As of right now a new dio client is being created  for every request made in [sas_api.dart]( https://github.com/joaoalves03/goipvc/blob/main/lib/services/sas_api.dart). Creating a class scoped Dio instance can reduce request latency since the socket connection won't be closed.

**Comment by rodrigosa7** [comment]
Great suggestion, I believe is a good first issue for @sousa-andre to solve
